CREATE TABLE TB_PET (
id SERIAL NOT NULL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
description TEXT NOT NULL,
age INT NOT NULL,
adopted BOOLEAN NOT NULL,
image VARCHAR(255) NOT NULL,
shelter_id BIGINT NOT NULL,
FOREIGN KEY (shelter_id) REFERENCES TB_SHELTER(id)
)