CREATE TABLE TB_USER_ROLE (
user_id BIGINT NOT NULL,
role_id BIGINT NOT NULL,
CONSTRAINT PK_USER_ROLE PRIMARY KEY (user_id, role_id),
FOREIGN KEY (user_id) REFERENCES TB_USER(id),
FOREIGN KEY (role_id) REFERENCES TB_ROLE(id)
)

